# -*- coding: utf-8 -*-
"""ToolBuilding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10tNSBwamaYRcTChfP5HKk_iaGQYZa0n0
"""

########## 1. Import required libraries ##########
import pandas as pd
import numpy as np
import re
import nltk
from scipy.stats import wilcoxon
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import (accuracy_score, f1_score, roc_curve, auc)
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression # Added for comprehensive comparison
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download NLTK resources
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

########## 2. Preprocessing & Lemmatization ##########
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def advanced_clean(text):
    text = re.sub(r'<.*?>', '', str(text)) # Remove HTML
    text = re.sub(r"[^A-Za-z]", " ", text) # Remove non-alpha
    words = text.lower().split()
    # Lemmatization: Reduce feature space
    cleaned = [lemmatizer.lemmatize(w) for w in words if w not in stop_words]
    return " ".join(cleaned)

########## 3. Data Preparation ##########
project = 'pytorch'
path = f'datasets/{project}.csv'
df = pd.read_csv(path).sample(frac=1, random_state=999)

# Merge Title and Body
df['text'] = df.apply(lambda r: f"{r['Title']}. {r['Body']}" if pd.notna(r['Body']) else str(r['Title']), axis=1)
df['cleaned_text'] = df['text'].apply(advanced_clean)
X = df['cleaned_text']
y = df['class']

########## 4. The 3-Way Model ##########
REPEAT = 10
results = {
    'NB': {'acc': [], 'f1': [], 'auc': []},
    'RF': {'acc': [], 'f1': [], 'auc': []},
    'LR': {'acc': [], 'f1': [], 'auc': []}
}

for r in range(REPEAT):
    print(f"Running Experiment {r+1}/{REPEAT}...")
    X_train_raw, X_test_raw, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=r)

    # Vectorization
    tfidf = TfidfVectorizer(ngram_range=(1, 2), max_features=2000)
    X_train = tfidf.fit_transform(X_train_raw)
    X_test = tfidf.transform(X_test_raw)

    # --- MODEL 1: Baseline GaussianNB ---
    # NB requires dense data, others can stay sparse (more efficient)
    nb = GaussianNB()
    nb.fit(X_train.toarray(), y_train)
    y_pred_nb = nb.predict(X_test.toarray())
    results['NB']['f1'].append(f1_score(y_test, y_pred_nb, average='macro'))
    results['NB']['acc'].append(accuracy_score(y_test, y_pred_nb))

    # --- MODEL 2: Random Forest (Balanced) ---
    rf = RandomForestClassifier(random_state=42, class_weight='balanced')
    rf_grid = GridSearchCV(rf, {'n_estimators': [100, 200], 'max_depth': [None, 20]}, cv=3, n_jobs=-1)
    rf_grid.fit(X_train, y_train)
    y_pred_rf = rf_grid.best_estimator_.predict(X_test)
    results['RF']['f1'].append(f1_score(y_test, y_pred_rf, average='macro'))
    results['RF']['acc'].append(accuracy_score(y_test, y_pred_rf))

    # --- MODEL 3: Logistic Regression (Balanced) ---
    lr = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
    lr_grid = GridSearchCV(lr, {'C': [0.1, 1, 10]}, cv=3, n_jobs=-1)
    lr_grid.fit(X_train, y_train)
    y_pred_lr = lr_grid.best_estimator_.predict(X_test)
    results['LR']['f1'].append(f1_score(y_test, y_pred_lr, average='macro'))
    results['LR']['acc'].append(accuracy_score(y_test, y_pred_lr))

########## 5. Final Analytics & Error Analysis ##########

print("\n" + "="*30)
for model in ['NB', 'RF', 'LR']:
    print(f"{model} - Avg Acc: {np.mean(results[model]['acc']):.4f}, Avg F1: {np.mean(results[model]['f1']):.4f}")

# Statistical Test (Comparing Baseline NB to your best model - likely LR or RF)
stat, p = wilcoxon(results['NB']['f1'], results['LR']['f1'])
print(f"\nWilcoxon P-value (NB vs LR): {p:.5f}")
if p < 0.05:
    print("Improvement is Statistically Significant!")

# Error Analysis Example for Report
error_analysis = pd.DataFrame({
    'Text': X_test_raw,
    'Actual': y_test,
    'Pred': y_pred_lr # Using LR as example
})
mismatches = error_analysis[error_analysis['Actual'] != error_analysis['Pred']]
print("\n--- Sample Misclassifications (Error Analysis) ---")
print(mismatches.head(3))

"""#GRAPHS"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# 1. Generate the Confusion Matrix for the best model (LR)
# Using the y_test and y_pred_lr from your final experiment run
cm = confusion_matrix(y_test, y_pred_lr)

# 2. Plotting
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Not Bug (0)', 'Bug (1)'],
            yticklabels=['Not Bug (0)', 'Bug (1)'])

plt.xlabel('Predicted Label', fontsize=12)
plt.ylabel('True Label', fontsize=12)
plt.title('Confusion Matrix: Logistic Regression Tool', fontsize=14, fontweight='bold')


plt.savefig('confusion_matrix.png', dpi=300)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# 1. Prepare Data
models = ['Naive Bayes\n(Baseline)', 'Random Forest', 'Logistic Regression\n(Proposed)']
accuracies = [0.8331, 0.8775, 0.8808]
f1_scores = [0.5722, 0.5162, 0.7280]

x = np.arange(len(models))
width = 0.35

# 2. Create Comparison Bar Chart
plt.figure(figsize=(10, 6))
plt.bar(x - width/2, accuracies, width, label='Accuracy', color='#AED6F1', edgecolor='black')
plt.bar(x + width/2, f1_scores, width, label='F1-Score', color='#FAD7A0', edgecolor='black')

plt.ylabel('Score (0.0 - 1.0)')
plt.title('Performance Comparison: Baseline vs. Proposed Tool')
plt.xticks(x, models)
plt.legend()
plt.ylim(0, 1.0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.savefig('performance_comparison.png', dpi=300)

# 3. Create Box Plot for F1 Scores

plt.figure(figsize=(8, 6))
plt.boxplot([results['NB']['f1'], results['RF']['f1'], results['LR']['f1']],
            labels=models, patch_artist=True)
plt.title('F1-Score Distribution (10 Repeated Runs)')
plt.ylabel('F1-Score')
plt.savefig('f1_stability.png', dpi=300)

